on: [push]
name: Shangshield.ml CI
permissions: read-all
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OCaml.
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: "Install dependencies."
        run: opam install .
          
      - name: "Run unit tests."
        run: opam exec -- dune runtest
      
      - name: "Run a documentation build."
        run: opam exec -- dune build @doc
      
      - name: "Run the linter."
        run: opam exec -- dune fmt